### ISSUE TITLE
Jack2 inside a docker container that doesn't use any sound card leads to Bus Error

### ISSUE THREAD

**Issue by nestarz** [jackaudio/jack2#745]
## Describe the bug

Trying to make work **jack2 in a docker container** with **only** a dummy driver to be used later with supercolider and sonic-pi in a VPS (no sound card).

## Env

docker-compose.yml
```yml
version: "3.9"
services:
  sonic-pi-server:
    cap_add: [SYS_NICE]
    shm_size: 256
    build: .
    ports:
      - "8000:8000"
      - "4557:4557"
    volumes:
      - ./data/:/home/developer/data
    ulimits:
      rtprio: 99
      memlock: -1
```

```Dockerfile
FROM debian:sid

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ARG VERSION_TAG="v1.9.17"

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
          git \
          gcc \
          g++

RUN apt update && apt install -y --no-install-recommends python3
RUN mkdir /tmp/jackd-compile \
        && git clone --recursive --depth 1 --branch ${VERSION_TAG} \
        git://github.com/jackaudio/jack2 /tmp/jackd-compile
  
ARG CC=/usr/bin/gcc
ARG CXX=/usr/bin/g++

WORKDIR /tmp/jackd-compile
RUN ./waf configure --debug --alsa=no --firewire=no --iio=no --portaudio=no --winmme=no --celt=no 
RUN ./waf build
RUN ./waf install
RUN ldconfig

RUN echo "@audio - memlock unlimited" >> /etc/security/limits.conf \
        && echo "@audio - rtprio 99" >> /etc/security/limits.conf

RUN mkdir /home/developer
WORKDIR /home/developer
COPY . /home/developer/app

ENTRYPOINT ["tail", "-f", "/dev/null"]
CMD jackd -r -d dummy -r 44100
```

### Expected vs. actual behavior

```bash
**root@a77d6eaccfab:/home/developer# jackd -r -d dummy -r 44100**
jackdmp 1.9.17
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2021 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
**Bus error**
```

I am trying to understand how I can get rid of Bus error ?
